#!/bin/sh
service=pop3d
. /usr/share/qmail/run-functions
hostname="`hostname`"
readdefault concurrency concurrencypop3d 20
readdefault checkpass checkpassword checkpassword
do_ulimits

exec tcpserver -dHRvX -c "$concurrency" \
	-x /etc/tcpcontrol/pop-3.cdb 0 pop-3 \
	qmail-popup "$hostname" \
	$checkpass \
	qmail-pop3d Maildir/
