#!/bin/sh
. /usr/share/qmail/run-functions
readdefault concurrency concurrencyqmqpd 20
readdefault ulimitdata ulimitdata 3000000

exec \
softlimit -m $ulimitdata \
envuidgid qmaild \
tcpserver -dRUvX -c "$concurrency" -x /etc/tcpcontrol/qmqp.cdb 0 628 \
qmail-qmqpd
