#!/bin/sh
service=qmqpd
. /usr/share/qmail/run-functions
readdefault concurrency concurrencyqmqpd 20
do_ulimits

exec envuidgid qmaild \
tcpserver -dRUvX -c "$concurrency" \
	-x /etc/tcpcontrol/qmqp.cdb 0 628 qmail-qmqpd
