#!/bin/sh
. /usr/lib/qmail/run-functions
readdefault concurrency concurrencyqmtpd 20
do_ulimits
cd /var/log
exec envuidgid qmaild \
tcpserver -U -c "$concurrency" -v -X \
	-x /etc/tcpcontrol/qmtp.cdb 0 209 qmail-qmtpd
