#!/bin/sh
. /usr/share/qmail/run-functions
readdefault concurrency concurrencyqmtpd 20
readdefault ulimitdata ulimitdata 2000000

exec \
softlimit -m $ulimitdata \
envuidgid qmaild \
tcpserver -DRUvX -c "$concurrency" -x /etc/tcpcontrol/qmtp.cdb 0 209 \
qmail-qmtpd
