#!/bin/sh
. /usr/share/qmail/run-functions

# If rblsmtpd is installed, process rbltimeout rbldomains, and antirbldomains
if [ -x /usr/bin/rblsmtpd ]; then
	readdefault domains antirbldomains ""
	for domain in $domains; do
		rblopts="$rblopts -a $domain"
	done
	readdefault domains rbldomains ""
	for domain in $domains; do
		rblopts="$rblopts -r $domain"
	done
	readdefault timeout rbltimeout 60
	if [ -n "$rblopts" ]; then
		rbl="/usr/bin/rblsmtpd -t $timeout $rblopts"
	fi
fi

# Start daemons.
readdefault concurrency concurrencysmtpd 20
do_ulimits

exec envuidgid qmaild \
tcpserver -DUXv -c "$concurrency" -l "`head -1 /var/qmail/control/me`" \
	-x /etc/tcpcontrol/smtp.cdb 0 smtp \
	fixcrio $rbl qmail-smtpd
