#!/bin/sh
service=spop3d
. /usr/lib/qmail/run-functions
hostname="`hostname`"
readdefault concurrency concurrencyspop3d 20
readdefault checkpass checkpassword checkpassword
do_ulimits

exec tcpserver -c "$concurrency" -v -R -X -D \
	-x /etc/tcpcontrol/pop-3.cdb 0 pop-3 \
	qmail-popup "$hostname" \
	$checkpass \
	qmail-spop3d Maildir/
